[tool.ruff]
select = ["I"]
fixable = ["I"]
target-version = "py310"
include = ["*.py"]
line-length = 119

[tool.ruff.isort]
combine-as-imports = true
known-first-party = ["musubi_restapi"]
section-order = ["future", "standard-library", "third-party", "first-party", "local-folder"]
split-on-trailing-comma = true

[tool.ruff.format]
quote-style = "double"
